# serverless.yml

service: french-verbs-app

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-webpack-prisma

package:
  patterns:
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-rhel-*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'
    
provider:
  name: aws
  runtime: nodejs16.x
  stage: prod
  region: eu-west-2

custom:
  webpack:
    webpackConfig: "webpack.config.js" # Name of webpack configuration file
    includeModules: true # Node modules configuration for packaging
    # packager: "npm" # Packager that will be used to package your external modules
    packagerOptions:
      scripts:
        - prisma generate

functions:
  app:
    handler: app.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
