# serverless.yml
 
service: french-verbs-app

plugins:
  - serverless-plugin-typescript
  - serverless-offline
 
provider:
  name: aws
  runtime: nodejs16.x
  stage: prod
  region: eu-west-2

custom:
  serverlessPluginTypescript:
    tsConfigFileLocation: './tsconfig.json'
 
functions:
  app:
    handler: app.handler
    events:
      - http: 
          method: ANY
          path: /{proxy+}
